# Generated by Django 4.0.2 on 2022-02-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbridgeforbillions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Not binary')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='status',
            field=models.BooleanField(),
        ),
    ]
